version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rest_api
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=rest_api
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  app:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - '8000:8000'
    depends_on:
      - db
volumes:
  db:
    driver: local