FROM --platform=$BUILDPLATFORM python:3.10 AS builder

EXPOSE 8000

WORKDIR /app

COPY requirements.txt /app

RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy everything
COPY ./ /app

ENTRYPOINT ["python3"]

COPY --from=gloursdocker/docker / /

ENTRYPOINT "./script/startup.sh"
