# Generated by Django 4.1.7 on 2023-03-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20230228_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='tier',
            name='sizes_of_thumb',
            field=models.JSONField(default={'1': '200'}),
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.tier'),
        ),
    ]
