# Generated by Django 4.1.7 on 2023-02-28 10:35

from django.db import migrations
from rest_api.models import Tier

def add_default_tiers(apps, schema_editor):
    tier = apps.get_model('rest_api', 'Tier')

    tier.objects.create(name="Basic", original_image = False, sizes_of_thumb = {"2":"200"})
    tier.objects.create(name="Premium", original_image = True, sizes_of_thumb = {"2":"200"})
    tier.objects.create(name="Enterprise", original_image = True, sizes_of_thumb = {"2":"200"})


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_tiers)
    ]
