# Generated by Django 4.1.7 on 2023-03-03 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_image_size_alter_tier_sizes_of_thumb_alter_user_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='static/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
    ]
